### ISSUE TITLE
Make a demo

### ISSUE THREAD

**Issue by kentcdodds** [abpetkov/transitionize#1]
Many devs (like myself) wont look too long at the documentation, unless we're wowed by a demo. Definitely recommend a demo for this :+1:

**Comment by abpetkov** [comment]
Added a example to demostrate a simple case. Check out commit <a href="https://github.com/abpetkov/transitionize/commit/96fc67ffe0d4670b76a675a2b2de2e570a3b2fd0">96fc67f</a>.
