### ISSUE TITLE
Bower version mismatch

### ISSUE THREAD

**Issue by ellisio** [abpetkov/transitionize#2]
Hello,

When I install your `switchery` library I get the following from Bower:

```
bower transitionize#*         mismatch Version declared in the json (0.0.2) is different than the resolved one (0.0.3)
```

This is because your Github tag of `0.0.3` is pointing to a `bower.json` that contains `0.0.2`.

Cheers,
Andrew

**Comment by abpetkov** [comment]
Hello Andrew,

Are you using the latest version of Switchery? I can't reproduce this issue. Can you provide some more details on how to cause this to happen? My install seems to be running fine:

![image 2015-05-01 at 13-15-36](https://cloud.githubusercontent.com/assets/1809512/7429098/44ee58d0-f004-11e4-8a45-67820ffa1bfd.png)

**Comment by ellisio** [comment]
Yes, the right "tagged" versions come down. But look at your `bower.json@0.0.3`:

https://github.com/abpetkov/transitionize/blob/0.0.3/bower.json#L4

Notice the version string is still 0.0.2? This is the issue.

Cheers,
Andrew

**Comment by abpetkov** [comment]
Fair enough. I think it's good now.

Thanks for escalating.

**Comment by ellisio** [comment]
No problem :) I only caught this because I have `silent: true` in my config and this bubbled up during our latest deployment.
